# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  snyk-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Snyk CLI  # Installs the Snyk CLI tool
        run: | 
          npm install -g snyk
      - name: Run Snyk Code scan  # Runs Snyk Code to scan for vulnerabilities
        run: snyk code test --severity-threshold=medium
        
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
